Repository heeyoung-c/react-kdt-mini-project-team1, pull requests merged in 2022-09, with the labels that each got.

#63 Wish products/#20
  src/api/productsApi.js
  src/components/ui/Card/index.jsx
  src/components/ui/Card/style.js
  src/pages/AllProducts/index.jsx
  src/pages/Cart/index.jsx
  src/pages/Cart/style.js
  src/pages/WishProducts/index.jsx
  src/store/index.js
  src/store/slices/counterSlice.js
Labels: 🔨Refactor, ✨Feature, 📬 API

#72 ♻️[refactor]: CustomProducts 데이터 출력코드수정/#71
  src/pages/CustomProducts/index.jsx
Labels: 🔨Refactor

#75 💄[design: 햄버거모달 스타일수정/#73
  src/components/Modal/hamburger.jsx
  src/components/Modal/style.js
  src/components/ui/UserCard/style.js
Labels: 💄design

#78 [feat][design]Entry/#69
  src/components/layout/TheFooter/index.jsx
  src/pages/Entry/Index.jsx
  src/pages/Entry/style.js
  src/pages/SignIn/style.js
  src/routes/AppRouter.jsx
  src/routes/PrivateRoute/index.jsx
Labels: ✨Feature, 💄design

#83 💄 design: footer 디자인 수정#81
  src/components/layout/TheFooter/index.jsx
  src/components/layout/TheFooter/style.js
Labels: 💄design

#88 [design][chore]SignIn/#87
  src/pages/Entry/style.js
  src/pages/SignIn/index.jsx
  src/pages/SignIn/style.js
  src/pages/SignUp/index.jsx
  src/pages/SignUp/style.js
  src/routes/PrivateRoute/index.jsx
Labels: 💄design

#90 💄[design]: modal 위치 수정 및 usercard글자수정/#89
  src/components/layout/TheHeader/style.js
  src/components/ui/UserCard/index.jsx
  src/components/ui/UserCard/style.js
Labels: 💄design

#91 [feat][design]Cart detail/#74
  src/api/productsApi.js
  src/components/layout/TheHeader/index.jsx
  src/components/layout/TheHeader/style.js
  src/components/ui/Card/index.jsx
  src/components/ui/EmptyProducts/index.jsx
  src/components/ui/EmptyProducts/style.js
  src/pages/Cart/index.jsx
  src/pages/Cart/style.js
  src/pages/CustomProducts/index.jsx
  src/pages/WishProducts/index.jsx
Labels: ✨Feature, 💄design

#98 [config]Modal/파일이름수정/#97
  src/components/Modal/index.jsx
  src/components/layout/TheHeader/index.jsx
  src/components/ui/UserCard/index.jsx
Labels: 🔧setting

#99 Sign in/#93
  src/components/ui/Input/index.jsx
  src/components/ui/TheButton/index.jsx
  src/components/ui/TheButton/style.js
  src/hooks/useForm.js
  src/pages/SignUp/index.jsx
  src/utils/validator.js
Labels: :bug: BugFix, ✨Feature, 💄design

#105 SignIn/#104
  src/pages/SignIn/style.js
  src/pages/SignUp/index.jsx
  src/pages/SignUp/style.js
Labels: 💄design
