Repository heeyoung-c/react-kdt-mini-project-team1, pull requests merged in 2022-08, with the labels that each got.

#4 The header/#1
  src/App.jsx
  src/components/layout/TheHeader/index.jsx
  src/components/layout/TheHeader/style.js
  src/styles/globalStyle.js
  src/styles/theme.js
Labels: ✨Feature, 💄design

#7 [conf]Json server/#6
  db.json
  package.json
  yarn.lock
Labels: 🔧setting

#13 [feat][design]Cart/#9
  package.json
  src/components/layout/TheHeader/index.jsx
  src/components/layout/TheHeader/style.js
  src/pages/AllProducts/index.jsx
  src/pages/Cart/index.jsx
  src/pages/Cart/style.js
Labels: ✨Feature, 💄design

#19 [feat][design]Sign up/#5
  src/components/ui/Input/index.jsx
  src/components/ui/Input/style.js
Labels: ✨Feature, 💄design

#25 [feat]Wish products/#20
  .gitignore
  src/api/postApi.js
  src/api/productsApi.js
  src/pages/WishProducts/index.jsx
  src/store/index.js
Labels: ✨Feature, 📬 API

#58 [config]:store index에 customApi.middleware추가/#56
  src/store/index.js
Labels: 🔧setting

#59 [config]: eslint 오류 해결/#44
  src/App.jsx
  src/components/layout/TheFooter/style.js
Labels: 🔧setting

#60 [feat][api]Custom products/#54
  src/api/customApi.js
  src/pages/CustomProducts/index.jsx
Labels: ✨Feature, 📬 API

#61 [feat][api]Modal user api출력/#55
  src/components/Modal/hamburger.jsx
Labels: ✨Feature, 📬 API

#62 [feat][api]: usercard 컴포넌트에서 user api 출력/#57
  src/components/ui/UserCard/index.jsx
Labels: ✨Feature, 📬 API
